# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 09:52
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelToListen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channelId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentId', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('likeCount', models.IntegerField()),
                ('publishedAt', models.DateTimeField()),
                ('textDisplay', models.TextField()),
                ('textOriginal', models.TextField()),
                ('updatedAt', models.DateTimeField()),
                ('videoId', models.CharField(max_length=100)),
                ('channelId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=100)),
                ('nbvideosvues', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('publishedAt', models.DateTimeField()),
                ('channelId', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.CharField(max_length=100)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('categoryId', models.IntegerField()),
                ('defaultLanguage', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField()),
                ('definition', models.CharField(max_length=100)),
                ('viewCount', models.IntegerField()),
                ('likeCount', models.IntegerField()),
                ('dislikeCount', models.IntegerField()),
                ('favoriteCount', models.IntegerField()),
                ('commentCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoToListen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('videoId', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parentCom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pere', to='dashboard.Comment'),
        ),
    ]
