# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nbvideosvues',
            new_name='nbvideoscommentees',
        ),
        migrations.AddField(
            model_name='user',
            name='nbLikes',
            field=models.IntegerField(default=0),
        ),
    ]
