# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180712_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replyCount',
            field=models.IntegerField(default=0),
        ),
    ]
