# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180713_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeltolisten',
            name='listening',
            field=models.BooleanField(default=False),
        ),
    ]
