# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_channeltolisten_listening'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelId', models.CharField(max_length=100)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('viewCount', models.IntegerField()),
                ('subscriberCount', models.IntegerField()),
                ('videoCount', models.IntegerField()),
                ('commentsCount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='channeltolisten',
            name='creationTime',
            field=models.DateTimeField(default='2009-06-19T04:24:41.000Z'),
        ),
        migrations.AddField(
            model_name='channeltolisten',
            name='description',
            field=models.TextField(default='nan'),
        ),
    ]
