# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180717_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeltolisten',
            name='commentsCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channeltolisten',
            name='subscriberCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channeltolisten',
            name='videoCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channeltolisten',
            name='viewCount',
            field=models.IntegerField(default=0),
        ),
    ]
