# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20180717_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channeltolisten',
            name='creationTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
