# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180717_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='userlink',
            old_name='value',
            new_name='weight',
        ),
    ]
