# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20180718_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelfeatures',
            name='commentersCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channelfeatures',
            name='modularity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='videolink',
            name='channelId',
            field=models.CharField(default='nan', max_length=100),
        ),
    ]
