# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20180718_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelId', models.CharField(max_length=100)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('viewCount', models.IntegerField(default=0)),
                ('subscriberCount', models.IntegerField(default=0)),
                ('commentersCount', models.IntegerField(default=0)),
                ('videoCount', models.IntegerField(default=0)),
                ('commentsCount', models.IntegerField(default=0)),
                ('pageRank', models.FloatField(default=0)),
            ],
        ),
    ]
