# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_userfeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeatures',
            name='SBMClass',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userfeatures',
            name='betweennessCentrality',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userfeatures',
            name='closenessCentrality',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userfeatures',
            name='degree',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userfeatures',
            name='harmonicClosenessCentrality',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userfeatures',
            name='louvainClass',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userfeatures',
            name='userId',
            field=models.CharField(default='nan', max_length=100),
        ),
    ]
