# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 09:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20180718_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfeatures',
            old_name='degree',
            new_name='weightedDegree',
        ),
        migrations.RemoveField(
            model_name='userfeatures',
            name='closenessCentrality',
        ),
        migrations.AddField(
            model_name='userfeatures',
            name='creationTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 9, 20, 59, 431998)),
        ),
        migrations.AddField(
            model_name='userfeatures',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userfeatures',
            name='nbLikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userfeatures',
            name='nbvideoscommentees',
            field=models.IntegerField(default=0),
        ),
    ]
