# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20180719_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeatures',
            name='creationTime',
            field=models.DateTimeField(),
        ),
    ]
