# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20180719_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='nan', max_length=100)),
                ('channelId', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('creationTime', models.DateTimeField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('viewCount', models.IntegerField(default=0)),
                ('subscriberCount', models.IntegerField(default=0)),
                ('commentersCount', models.IntegerField(default=0)),
                ('videoCount', models.IntegerField(default=0)),
                ('commentsCount', models.IntegerField(default=0)),
                ('pageRank', models.FloatField(default=0)),
                ('weightedDegree', models.IntegerField(default=0)),
                ('betweennessCentrality', models.FloatField(default=0)),
                ('nbLikes', models.IntegerField(default=0)),
                ('nbvideoscommentees', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='ChannelFeatures',
            new_name='ChannelFeature',
        ),
        migrations.RenameModel(
            old_name='VideoFeatures',
            new_name='VideoFeature',
        ),
        migrations.DeleteModel(
            name='UserFeatures',
        ),
    ]
