# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20180719_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeltolisten',
            name='listeningTime',
            field=models.CharField(default='', max_length=100),
        ),
    ]
