# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_channeltolisten_listeningtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeature',
            name='timeStamp',
            field=models.DateTimeField(),
        ),
    ]
