# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20180719_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channeltolisten',
            name='listeningTime',
            field=models.CharField(default='2018-07-19 11:58:07.046006+02', max_length=100),
        ),
    ]
