# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20180719_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channeltolisten',
            name='listeningTime',
            field=models.CharField(default='2018-07-19 12:32:12.371096', max_length=100),
        ),
    ]
