# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20180719_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videofeature',
            old_name='degree',
            new_name='weightedDegree',
        ),
        migrations.RemoveField(
            model_name='videofeature',
            name='SBMClass',
        ),
        migrations.RemoveField(
            model_name='videofeature',
            name='betweennessCentrality',
        ),
        migrations.RemoveField(
            model_name='videofeature',
            name='closenessCentrality',
        ),
        migrations.RemoveField(
            model_name='videofeature',
            name='harmonicClosenessCentrality',
        ),
        migrations.RemoveField(
            model_name='videofeature',
            name='louvainClass',
        ),
        migrations.AddField(
            model_name='videofeature',
            name='usersPower',
            field=models.IntegerField(default=0),
        ),
    ]
