# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20180725_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationVideoSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=100)),
                ('chosen', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=300)),
                ('maxDate', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='relationvideosearch',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Search'),
        ),
    ]
