# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20180725_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channelId', models.CharField(max_length=100)),
                ('listening', models.BooleanField(default=False)),
                ('creationTime', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='nan')),
                ('viewCount', models.IntegerField(default=0)),
                ('subscriberCount', models.IntegerField(default=0)),
                ('videoCount', models.IntegerField(default=0)),
                ('commentsCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RelationChannelSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelId', models.CharField(max_length=100)),
                ('chosen', models.BooleanField()),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Search')),
            ],
        ),
        migrations.DeleteModel(
            name='ChannelToListen',
        ),
        migrations.RemoveField(
            model_name='channelfeature',
            name='averagePathLength',
        ),
        migrations.RemoveField(
            model_name='channelfeature',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='channelfeature',
            name='modularity',
        ),
        migrations.RemoveField(
            model_name='relationvideosearch',
            name='chosen',
        ),
        migrations.AddField(
            model_name='channelfeature',
            name='betweennessCentrality',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='channelfeature',
            name='creationTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channelfeature',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='channelfeature',
            name='nbLikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channelfeature',
            name='nbvideoscommentees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channelfeature',
            name='pageRank',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='channelfeature',
            name='search',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Search'),
        ),
        migrations.AddField(
            model_name='channelfeature',
            name='weightedDegree',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='channelfeature',
            name='timeStamp',
            field=models.DateTimeField(),
        ),
    ]
