# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20180726_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='maxDate',
            field=models.DateTimeField(),
        ),
    ]
