# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_commenttexthyperlink_videodeschyperlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commenttexthyperlink',
            old_name='link',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='videodeschyperlink',
            old_name='link',
            new_name='url',
        ),
    ]
