# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20180801_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelfeature',
            name='search',
        ),
        migrations.DeleteModel(
            name='ChannelLink',
        ),
        migrations.DeleteModel(
            name='UserFeature',
        ),
        migrations.DeleteModel(
            name='UserLink',
        ),
        migrations.DeleteModel(
            name='VideoFeature',
        ),
        migrations.DeleteModel(
            name='VideoLink',
        ),
        migrations.DeleteModel(
            name='VideoToListen',
        ),
        migrations.DeleteModel(
            name='ChannelFeature',
        ),
    ]
